### ISSUE TITLE
[pesquisa_repercussãoGeral] Filtro de ministros

### ISSUE THREAD

**Issue by ElmarRoberto** [supremotribunalfederal/portalstf-static-frontend#3]
**Task** - Criar select múltiplo com listagem de cards dos ministros

**Critérios de aceitação**

- [x] Dropdown de ministros listando pequenos cards com a imagem e nome de cada um.

- [x] Link "mais detalhes" em cada card.

- [x] Pesquisa associada.

- [x] Múltiplo select.

- [x] Mostrar ministros selecionados.
